import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"




export default function Home() {
    const { data: session, status } = useSession()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Hello world!</h1>
                <h1>{status}</h1>
                <button onClick={() => signIn()}>Sign in</button>
                <button onClick={() => signOut()}>Sign Out</button>
            </main>
        </>
    )
}
